# Alt-e is prefix
unbind C-b
set-option -g prefix M-e
bind-key M-e send-prefix

# split panes by | and -
unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# reload config file
bind r source-file ~/.tmux.conf

# Alt to move panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# stop auto-renaming
set-option -g allow-rename off
# start with window 1
set -g base-index 1
# start with pane 1
set -g pane-base-index 1
# open new window with current pwd
bind c new-window -c "#{pane_current_path}"
# renumber on close
set -g renumber-windows on
# QoL
set -s escape-time 0
set -g focus-events on
# more history
set -g history-limit 10000

# set default terminal mode to 256 colors
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# mouse shizzle
set -g mouse on
set -g mode-keys vi
# yoinked but not sure if correct
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X stop-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy --trim-newline"
